### ISSUE TITLE
Unicode Fehler in der Übersicht

### ISSUE THREAD

**Issue by Mangnoppa** [eknoes/golem-android-reader#14]
In der Übersicht werden Unicode Zeichen nicht richtig dargestellt:

![unicode_fehler](https://user-images.githubusercontent.com/11314222/52470035-5cded000-2b8d-11e9-8885-846e5325b29d.png)

Im Artikel ist das richtige Zeichen zu sehen:

![unicode_ohne_fehler](https://user-images.githubusercontent.com/11314222/52470148-a4fdf280-2b8d-11e9-8a4b-fca4b084493e.png)

**Comment by eknoes** [comment]
Super, danke! Das sollte nicht passieren, ich schaue es mir mal an!
