### ISSUE TITLE
Keine Kommentare mit Premium

### ISSUE THREAD

**Issue by madejackson** [eknoes/golem-android-reader#2]
Link zu Kommentare werden nicht angezeigt, wenn Premium-Token eingegeben wird.

**Comment by eknoes** [comment]
Hi, das kann ich leider nicht ändern. Mit Golem Premium wird der Volltext RSS Feed genutzt, um Artikel anzuzeigen:
[https://rss.golem.de/rss_sub_media.php?token=XXX](https://rss.golem.de/rss_sub_media.php?token=) (XXX muss durch das eigene Token ersetzt werden).

Seit einiger Zeit ist im Volltext RSS Feed allerdings kein Kommentarlink mehr vorhanden. Ich habe erst vor kurzem Golem.de angeschrieben, ob sie einen Kommentarlink über die API bereitstellen können, damit ich das einbauen kann, und warte noch auf eine Antwort - Vielleicht wird das ja bald was!

**Comment by madejackson** [comment]
Schade...
Danke für die Info :)

**Comment by eknoes** [comment]
Hey, seit dem neuesten Release - aktuell nur in der [Beta Version](https://play.google.com/apps/testing/de.eknoes.inofficialgolem) im Play Store - gibt es einen Button, der direkt zu den Kommentaren führt!
