### ISSUE TITLE
Schriftgröße groß in Artikeln funktioniert nicht

### ISSUE THREAD

**Issue by Fl0r3** [eknoes/golem-android-reader#25]
Schriftgröße in einzelnen Artikeln ändert sich nur bei klein und normal, aber wird nicht groß. Auf der Startseite funktioniert große Schrift.

**Comment by eknoes** [comment]
Die App verlässt sich ab der kommenden Version auf die Accessability Einstellungen von Android und die eigenen Schriftgrößeneinstellungen wurden dafür entfernt, ist in 7d5693c03723fabd4da4623dd33d3752ad38fa81 geschehen.
