### ISSUE TITLE
Feature: Deeplinks

### ISSUE THREAD

**Issue by phireck999** [eknoes/golem-android-reader#27]
You can share links via click on share, but you can not get back into the app when clicking on them. Instead the user is sent to the external browser. It woul be nice to route any link with host www.golem.de back into the app via deeplink

**Comment by eknoes** [comment]
Would be a nice feature! I currently do not really have time to develop this app, but feel free to create a PR. Hope to have some time later this year to improve it.

**Comment by eknoes** [comment]
Should be available in the next hours via the beta track, you can join here: https://play.google.com/apps/testing/de.eknoes.inofficialgolem

The release to production might take another week or so, as I want to add some more features.
