### ISSUE TITLE
Schrift manchmal nicht lesbar

### ISSUE THREAD

**Issue by jurgispods** [eknoes/golem-android-reader#3]
Manchmal (von mir ist kein Muster erkennbar) ist die Schriftfarbe der Titel weiß und die des Teaser-Textes hellgrau, beides auf dem hellgrauen Hintergrund kaum erkennbar.

Wenn ich die App am nächsten Tag öffne, ist alles wieder wie gehabt. Ein einfaches Neuladen der Artikel oder ein Neustart der App helfen nicht.

Kontext:
App-Version 1.0.1
Android 7.1
OnePlus 3

**Comment by jurgispods** [comment]
Nach einiger Zeit kann ich mittlerweile doch ein Muster erkennen. Das Problem scheint nur abends aufzutreten, ich vermute also eine Art Nachtmodus dahinter.

**Comment by eknoes** [comment]
Das war der entscheidende Hinweis! Es gab mal die Bitte, ein "Dark Theme" zu bauen und irgendwie habe ich dort ein wenig herumgespielt - eine Komponente daraus ist ausversehen da geblieben und hat zu dem Verhalten geführt! Danke!
