### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [eknoes/golem-android-reader#30]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by eknoes** [comment]
Thanks for the hint, I thought I already did that but it seems I messed up with the directory structure. Lets see if F-Droid picks it up!
