### ISSUE TITLE
Links in articles not clickable

### ISSUE THREAD

**Issue by marcauberer** [eknoes/golem-android-reader#32]
Nothing is happening when clicking on links within articles

**Comment by eknoes** [comment]
Hi, I am currently quite busy and not really working on the app anymore, so I would be really glad for a PR. I think I can take a deeper look earliest in March.

I just tested it on my phone with the current Play Store version, can you confirm that just the external links do not work anymore? I guess if its the external links it might have to do something with the intent that should open them in a web browser over here: https://github.com/eknoes/golem-android-reader/blob/master/app/src/main/java/de/eknoes/inofficialgolem/GolemWebViewClient.java#L30

**Comment by marcauberer** [comment]
Yes, only external links are affected by this issue.

**Comment by eknoes** [comment]
Fixed in 6abcdd6, thanks @GLAD-DE
