### ISSUE TITLE
Werbung /Anzeigen in der App trotz eingerichtetem Token und abo

### ISSUE THREAD

**Issue by Krumbelfix** [eknoes/golem-android-reader#33]
In der Anwendung wird leider trotz einem eingerichtetem RSS-Token Werbung angezeigt.
Der RSS-Feed direkt aufgerufen zeigt keine Werbung.

**Comment by eknoes** [comment]
Danke für die Meldung, das sollte nicht passieren. Ich habe an der App schon länger nichts mehr gemacht, aber meine Vermutung ist, dass die App ja die alten Daten von dem RSS Feed mit Werbung noch in der Datenbank hat und nun nur die "nächsten" Werbeanzeigen nicht mehr angezeigt werden. Kann das sein? Also ist die Werbung von "bevor" du es eingerichtet hast? Oder kam auch welche danach?

**Comment by Krumbelfix** [comment]
Hi,
da das Abo seit langem Eingerichtet ist, und das Problem ebenfalls schon lange besteht, denke ich das nicht.
Es werden auch immer die neusten Anzeigen im Feed nachgeladen.
Aktuell wird die neuste Beta-Version der Anwendung genutzt.
Folgende EInstellungen sind gesetzt:
Anzahl der Artikel: 200
Aktualisierungsintervall: 50 Min
Ansicht:
   id: generic_android_ver4
   Marke: generic
   Modell: Android 4.0
   System: Android (4.0)
   Drahtlos: ja
   Ansicht: Mobile

Der Darkmode wird genutzt.
Als Smartphone kommt ein OnePlus 6T mit Android 10 zum Einsatz.
Die Installation der Anwendung erfolgte aus dem Google-Playstore

**Comment by eknoes** [comment]
Alles klar. Kannst du nochmal verifizieren, dass die Anzeigen nicht in diesem RSS Feed auftauchen? Das ist - soweit ich das gerade sehe - der einzige, der abgerufen wird:
https://rss.golem.de/rss_sub_media.php?token=GOLEM_TOKEN

**Comment by Krumbelfix** [comment]
Hi,

das habe ich verifiziert.
Die Anzeige (bspw. 24-Stunden-Deals bei Media Markt  Saturn) erscheinen nicht im RSS-Feed.
In der App sind sie jedoch zu sehen.

**Comment by eknoes** [comment]
Alles klar. Ich habe gerade leider kein Golem Abo um das zu testen. Ich schaue mir das mal an, wenn ich die Zeit finde, freue mich aber sehr über andere die einen PR machen, da ich die App selbst eigentlich nicht mehr nutze!
