### ISSUE TITLE
Automatisches aktualisieren deaktivieren. 

### ISSUE THREAD

**Issue by StevNash1337** [eknoes/golem-android-reader#4]
Ich fände es gut, wenn man das automatische aktualisieren deaktivieren kann. Das geht erstens aufs Datenvolumen (wegen der Bilder) und zweitens möchte ich manchmal noch alte Artikel lesen. Mir geht da so ein bisschen die Kontrolle verloren. 
Der Wert 0 beim Slider könnte ja für "aus" stehen, so wie es intuitiv viele Apps verwenden.

**Comment by eknoes** [comment]
Gute Idee, habe ich noch nie drüber nachgedacht! Update sollte heute noch verfügbar sein :)
