### ISSUE TITLE
Anzeigen / Kein Artikeldownload trotz Abo

### ISSUE THREAD

**Issue by ghstljsa** [eknoes/golem-android-reader#8]
Hi,
ich hab ein Abo (und auch "Golem.de Abo nutzen") angehakt. Trotzdem werden nicht alle Artikel runtergeladen (und sind deswegen nicht offline verfügbar) und einige Artikel haben Anzeigen.
Woran kann dass liegen, mache ich was falsch?
Grüße
Stephan Tautz

**Comment by eknoes** [comment]
Die Artikel, welche nicht heruntergeladen werden konnten, sind wahrscheinlich auch die mit Anzeigen, oder nicht?

Es ist ein Fehler bei Golem.de, der Volltext RSS Feed aus dem die offline Artikel kommen beinhaltet aktuell nicht alle Artikel, die verfügbar sind. Bei mir ist das aktuell z.B. bei "Google: Chromebooks bekommen "Linux-VMs" und "Terminal"" der Fall. Kannst du das verifizieren?

**Comment by ghstljsa** [comment]
Ja und ja. 

 

Gibt’s dazu ne Stellungsnahme von Golem.de? 

 

==> Wenn nich, würd ich dann mal nachfragen wozu ich 30€ im Jahr bezahl…

 

UND: vielen Dank für die schnelle Antwort!

 

Von: Sönke [mailto:notifications@github.com] 
Gesendet: Dienstag, 27. Februar 2018 17:06
An: eknoes/golem-android-reader <golem-android-reader@noreply.github.com>
Cc: ghstljsa <gh.st@ljsa.de>; Author <author@noreply.github.com>
Betreff: Re: [eknoes/golem-android-reader] Anzeigen / Kein Artikeldownload trotz Abo (#8)

 

Die Artikel, welche nicht heruntergeladen werden konnten, sind wahrscheinlich auch die mit Anzeigen, oder nicht?

Es ist ein Fehler bei Golem.de, der Volltext RSS Feed aus dem die offline Artikel kommen beinhaltet aktuell nicht alle Artikel, die verfügbar sind. Bei mir ist das aktuell z.B. bei "Google: Chromebooks bekommen "Linux-VMs" und "Terminal"" der Fall. Kannst du das verifizieren?

**Comment by eknoes** [comment]
Ich habe die Golem Redaktion mal per Mail informiert und geb Bescheid, wenn es eine Rückmeldung gibt.

**Comment by ghstljsa** [comment]
Danke!

Von meinem Android-Telefon mit TouchDown (www.symantec.com) gesendet

-----Original Message-----

**Comment by eknoes** [comment]
Golem hat sich mittlerweile zurück gemeldet, sie haben das Problem behoben.

**Comment by ghstljsa** [comment]
Danke!

 

Von: Sönke [mailto:notifications@github.com] 
Gesendet: Freitag, 2. März 2018 09:24
An: eknoes/golem-android-reader <golem-android-reader@noreply.github.com>
Cc: ghstljsa <gh.st@ljsa.de>; Author <author@noreply.github.com>
Betreff: Re: [eknoes/golem-android-reader] Anzeigen / Kein Artikeldownload trotz Abo (#8)

 

Golem hat sich mittlerweile zurück gemeldet, sie haben das Problem behoben.
